import { Evidence } from '../components/findings/Evidence';
import { useMemo, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { Check, Copy, Search } from 'lucide-react';
import type { Finding } from '../api/types';
import { StatusBadge } from '../components/ui';

const severities = ['', 'INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL'];
const modules = ['', 'dataset_integrity', 'model_integrity', 'inference_integrity', 'distribution_shift'];
const recommendations = ['', 'ACCEPT', 'REVIEW', 'QUARANTINE', 'REJECT'];

export function FindingsPage({ findings, limited = false }: { findings: Finding[]; limited?: boolean }) {
  const [params, setParams] = useSearchParams();
  const [selectedId, setSelectedId] = useState(findings[0]?.finding_id ?? '');
  const [copy, setCopy] = useState('');
  const filtered = useMemo(() => findings.filter((item) => (!params.get('severity') || item.severity === params.get('severity')) && (!params.get('module') || item.module === params.get('module')) && (!params.get('recommendation') || item.recommendation === params.get('recommendation')) && (!params.get('q') || `${item.finding_id} ${item.category} ${item.asset_id}`.toLowerCase().includes(params.get('q')!.toLowerCase()))), [findings, params]);
  const selected = filtered.find((item) => item.finding_id === selectedId) ?? filtered[0];
  const update = (key: string, value: string) => { const next = new URLSearchParams(params); if (value) next.set(key, value); else next.delete(key); setParams(next); };
  const copyText = async (value: string, key: string) => { await navigator.clipboard.writeText(value); setCopy(key); };
  return <div className="reference-page findings-page">
    <header className="reference-page-header"><div><span>FINDINGS</span><h1>Findings</h1><p>{findings.length} findings require attention.</p></div><label className="findings-search"><Search /><input aria-label="Category or asset search" placeholder="Search ID, category, asset…" value={params.get('q') ?? ''} onChange={(event) => update('q', event.target.value)} /></label></header>
    {limited && <div className="contract-note">Showing the latest authenticated summary subset.</div>}
    <div className="findings-layout"><section className="findings-main"><div className="filter-bar"><Filter label="Severity" value={params.get('severity') ?? ''} values={severities} onChange={(value) => update('severity', value)} /><Filter label="Module" value={params.get('module') ?? ''} values={modules} onChange={(value) => update('module', value)} /><Filter label="Recommendation" value={params.get('recommendation') ?? ''} values={recommendations} onChange={(value) => update('recommendation', value)} /></div><div className="explorer-head"><span>ID / CAT</span><span>ASSET</span><span>SHORT REASON</span><span>CONF.</span><span>ACTION</span></div><div className="explorer-list">{filtered.map((item) => <button key={item.finding_id} className={`explorer-row severity-${item.severity.toLowerCase()}${selected?.finding_id === item.finding_id ? ' selected' : ''}`} onClick={() => setSelectedId(item.finding_id)}><i /><span><code>{item.finding_id}</code><b>{item.category.replaceAll('_', ' ')}</b></span><span><code title={item.asset_id}>{item.asset_id}</code></span><span><small>{item.reason}</small></span><span><b>{Math.round(item.confidence * 100)}%</b></span><span><StatusBadge value={item.recommendation} /></span></button>)}{!filtered.length && <div className="workspace-empty">No loaded findings match these filters.</div>}</div></section>
      <aside className="inspector finding-inspector" aria-label="Finding details">{selected ? <><div className="finding-inspector-head"><div><code>{selected.finding_id}</code><strong>{selected.category.replaceAll('_', ' ')}</strong></div><b>{Math.round(selected.confidence * 100)}%<small>CONF</small></b></div><CopyField value={selected.finding_id} label="FINDING ID" copied={copy === 'finding'} onCopy={() => copyText(selected.finding_id, 'finding')} /><span className="inspector-label">FINDING DETAILS</span><dl><div><dt>MODULE</dt><dd>{selected.module === 'distribution_shift' ? 'Distribution Shift' : selected.module.replaceAll('_', ' ')}</dd></div><div><dt>ASSET TYPE</dt><dd>{selected.asset_type}</dd></div><div><dt>ASSET ID</dt><dd><code title={selected.asset_id}>{selected.asset_id}</code></dd></div><div><dt>SEVERITY</dt><dd><StatusBadge value={selected.severity} /></dd></div></dl><CopyField value={selected.asset_id} label="ASSET ID" copied={copy === 'asset'} onCopy={() => copyText(selected.asset_id, 'asset')} /><section><h2>WHY WAS THIS FLAGGED?</h2><p>{selected.reason}</p></section><Evidence evidence={selected.evidence} /><details open><summary>RECOMMENDATION</summary><StatusBadge value={selected.recommendation} /></details><details open><summary>LIMITATIONS</summary>{selected.limitations.length ? <ul>{selected.limitations.map((item, index) => <li key={index}>{item}</li>)}</ul> : <p>No finding-specific limitations supplied.</p>}</details><div className="analyst-actions" aria-label="Analyst actions unavailable"><button disabled title="Analyst action workflow is not enabled in this build">ACCEPT</button><button disabled title="Analyst action workflow is not enabled in this build">REVIEW</button><button disabled title="Analyst action workflow is not enabled in this build">QUARANTINE</button></div></> : <div className="workspace-empty">Select a finding.</div>}</aside>
    </div>
  </div>;
}

function Filter({ label, value, values, onChange }: { label: string; value: string; values: string[]; onChange: (value: string) => void }) { return <label><span>{label.toUpperCase()}</span><select aria-label={label} value={value} onChange={(event) => onChange(event.target.value)}>{values.map((item) => <option key={item} value={item}>{item === 'distribution_shift' ? 'Distribution Shift' : item ? item.replaceAll('_', ' ') : 'ALL'}</option>)}</select></label>; }
function CopyField({ value, label, copied, onCopy }: { value: string; label: string; copied: boolean; onCopy: () => void }) { return <div className="copy-field"><span><small>{label}</small><code title={value}>{value}</code></span><button onClick={onCopy} aria-label={`Copy ${label.toLowerCase()}`}>{copied ? <><Check />Copied</> : <><Copy />Copy</>}</button></div>; }
