import type{ButtonHTMLAttributes,HTMLAttributes,ReactNode}from'react';import{AlertTriangle,WifiOff}from'lucide-react';import clsx from'clsx';
export function Card({className,...p}:HTMLAttributes<HTMLElement>){return <section className={clsx('card',className)} {...p}/>}
export function Badge({tone='neutral',children,className}:{tone?:string;children:ReactNode;className?:string}){return <span className={clsx('badge',`tone-${tone.toLowerCase()}`,className)}>{children}</span>}
export function Button({className,...p}:ButtonHTMLAttributes<HTMLButtonElement>){return <button className={clsx('button',className)} {...p}/>}
export function Skeleton({className}:{className?:string}){return <div aria-hidden="true" className={clsx('skeleton',className)}/>}
export function LoadingDashboard(){return <div aria-label="Loading assurance dashboard" role="status" className="loading-grid"><Skeleton className="sk-hero"/>{[1,2,3,4].map(i=><Skeleton key={i} className="sk-module"/>)}<Skeleton className="sk-wide"/></div>}
export function ErrorState({offline=false,message,onRetry}:{offline?:boolean;message:string;onRetry:()=>void}){const Icon=offline?WifiOff:AlertTriangle;return <div className="failure-page"><header className="failure-heading"><span className="eyebrow">ASSURANCE OVERVIEW</span><h1>Assurance command center</h1><p>Local assessment assurance and integrity status</p></header><Card className="state-card" role="alert"><Icon/><span className="state-kicker">LOCAL SERVICE STATUS</span><h2>{offline?'BACKEND OFFLINE':'ASSURANCE VIEW UNAVAILABLE'}</h2><p>{offline?'DRISHTI could not reach the local assurance backend.':message}</p>{offline&&<p className="state-detail">Backend: <code>{import.meta.env.VITE_DRISHTI_API_URL??'http://127.0.0.1:8000'}</code></p>}<div className="state-actions"><Button onClick={onRetry}>RETRY CONNECTION</Button>{offline&&<span>Demo data is never loaded automatically.<br/><code>Restart with VITE_DRISHTI_DEMO_MODE=true</code></span>}</div>{!offline&&<details><summary>Technical detail</summary><p>{message}</p></details>}</Card></div>}
export const toneFor=(value:string)=>value==='GOOD'||value==='ACCEPT'||value==='VALID'||value==='ONLINE'?'success':value==='WATCH'||value==='REVIEW'||value==='PROVISIONAL'||value==='DEGRADED'?'warning':value==='HIGH_RISK'||value==='QUARANTINE'||value==='REJECT'||value==='CRITICAL'||value==='COMPROMISED'||value==='HIGH'?'danger':value==='MEDIUM'?'warning':'neutral';
export function StatusBadge({value}:{value:string}){return <Badge tone={toneFor(value)}>{value.replaceAll('_',' ')}</Badge>}
