import { cleanup, render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { MemoryRouter } from 'react-router-dom';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

async function renderDemo(scenario = 'critical') { vi.resetModules(); vi.stubEnv('VITE_DRISHTI_DEMO_MODE', 'true'); vi.stubEnv('VITE_DRISHTI_SUBMISSION_PREVIEW', 'false'); vi.stubEnv('VITE_DRISHTI_DEMO_SCENARIO', scenario); const { default: App } = await import('../App'); return render(<MemoryRouter><App /></MemoryRouter>); }
afterEach(() => cleanup());

describe('DRISHTI reference UI', () => {
  afterEach(() => { vi.unstubAllEnvs(); vi.restoreAllMocks(); });
  it('renders branding, selector, evidence counts and explicit demo provenance', async () => { await renderDemo(); expect((await screen.findAllByText('Drishti Trust'))[0]).toBeVisible(); expect(screen.getByText('DEMO DATA')).toBeVisible(); expect(screen.getByLabelText(/assessment/i)).toBeVisible(); expect(screen.getByText(/18 authenticated · 3 excluded/)).toBeVisible(); });
  it('renders findings, audit and accessible limitations', async () => { await renderDemo(); expect((await screen.findAllByText('REPLAY DETECTED')).length).toBeGreaterThan(0); expect(screen.getByText(/184 records checked/i)).toBeVisible(); expect(screen.getByText(/Signature validity authenticates provenance/)).toBeInTheDocument(); });
  it('renders null score as unavailable rather than zero', async () => { await renderDemo('unknown'); expect(await screen.findByLabelText('Assurance score unavailable')).toBeVisible(); expect(screen.getAllByText('UNAVAILABLE').length).toBeGreaterThan(0); expect(screen.queryByText(/^0\.0$/)).not.toBeInTheDocument(); });
  it('shows partial backend coverage and supplied disposition', async () => { await renderDemo('provisional'); expect(await screen.findByText(/Coverage 50%/)).toBeVisible(); expect(screen.getAllByText('PROVISIONAL').length).toBeGreaterThan(0); expect(screen.getAllByText('REVIEW').length).toBeGreaterThan(0); });
  it('assessment selection reloads the selected summary', async () => { await renderDemo(); const select = await screen.findByLabelText(/assessment/i); await userEvent.selectOptions(select, 'AST-CV-2026-011'); await waitFor(() => expect(select).toHaveValue('AST-CV-2026-011')); expect(screen.getAllByText('AST-CV-2026-011').length).toBeGreaterThan(0); });
  it('navigation is keyboard reachable', async () => { await renderDemo(); const link = await screen.findByRole('link', { name: 'Findings' }); link.focus(); expect(link).toHaveFocus(); await userEvent.keyboard('{Enter}'); expect(await screen.findByRole('heading', { name: 'Findings' })).toBeVisible(); });
});

describe('real backend states', () => {
  beforeEach(() => { vi.resetModules(); vi.stubEnv('VITE_DRISHTI_DEMO_MODE', 'false'); vi.stubEnv('VITE_DRISHTI_SUBMISSION_PREVIEW', 'false'); });
  afterEach(() => { vi.unstubAllEnvs(); vi.restoreAllMocks(); });
  it('shows skeleton then bounded offline state with no demo badge', async () => { let reject: (() => void) | undefined; vi.stubGlobal('fetch', vi.fn(() => new Promise((_resolve, fail) => { reject = () => fail(new TypeError('offline')); }))); const { default: App } = await import('../App'); render(<MemoryRouter><App /></MemoryRouter>); expect(screen.getByLabelText('Loading assurance dashboard')).toBeVisible(); await waitFor(() => expect(reject).toBeTypeOf('function')); reject?.(); expect(await screen.findByText(/backend offline/i)).toBeVisible(); expect(screen.queryByText('DEMO DATA')).not.toBeInTheDocument(); });
  it('handles no active assessment 404', async () => { const { demoScenarios } = await import('../fixtures/demo'); vi.stubGlobal('fetch', vi.fn((input: RequestInfo | URL) => { const url = String(input); const body: unknown = url.endsWith('/health') ? { status: 'ok', service: 'x', offline: 'true', audit_outbox_pending: 0, audit_outbox_healthy: true, audit_chain_valid: true } : url.includes('/current') ? { detail: 'No ACTIVE assessment' } : url.includes('/assessments?') ? { total: 0, limit: 100, offset: 0, items: [] } : demoScenarios.unknown; return Promise.resolve(new Response(JSON.stringify(body), { status: url.includes('/current') ? 404 : 200, headers: { 'Content-Type': 'application/json' } })); })); const { default: App } = await import('../App'); render(<MemoryRouter><App /></MemoryRouter>); expect(await screen.findByText(/No active assessment\. Select a historical/)).toBeVisible(); });
  it('renders compromised and unavailable audit values supplied by backend', async () => { const { OverviewPage } = await import('../pages/OverviewPage'); const { demoScenarios } = await import('../fixtures/demo'); const summary = demoScenarios.critical; const { rerender } = render(<MemoryRouter><OverviewPage summary={{ ...summary, audit_integrity: { status: 'COMPROMISED', records_checked: 14, first_broken_audit_id: 'AUD-01' } }} /></MemoryRouter>); expect(screen.getByText(/Audit COMPROMISED/)).toBeVisible(); expect(screen.getByText(/First broken record/)).toBeVisible(); rerender(<MemoryRouter><OverviewPage summary={{ ...summary, audit_integrity: { status: 'UNAVAILABLE', records_checked: null, first_broken_audit_id: null } }} /></MemoryRouter>); expect(screen.getByText(/Records unavailable/)).toBeVisible(); });
  it('shows a bounded server error', async () => { vi.stubGlobal('fetch', vi.fn(() => Promise.resolve(new Response('{}', { status: 500 })))); const { default: App } = await import('../App'); render(<MemoryRouter><App /></MemoryRouter>); expect(await screen.findByText(/backend offline/i)).toBeVisible(); });
});

it('fixtures retain backend contracts and helpers only format', async () => { const { demoScenarios } = await import('../fixtures/demo'); const { isSummary } = await import('../api/summary'); const { fmtPct, fmtScore } = await import('../components/assurance/Assurance'); Object.values(demoScenarios).forEach((item) => expect(isSummary(item)).toBe(true)); expect(fmtPct(.75)).toBe('75%'); expect(fmtScore(null)).toBe('Unavailable'); expect(fmtScore(78.4)).toBe('78.4'); });
